import config from '../lib/config';
import fonts from '../fonts';

export default {
  useCustomProperties: true,
  breakpoints: ['768px', '1024px', '1200px'],
  space: [0, 4, 8, 12, 16, 20, 24, 32, 40, 48, 56, 64, 72, 80, 128, 256, 512],
  sizes: [0, 4, 8, 12, 16, 20, 24, 32, 40, 48, 56, 64, 72, 80, 128, 256, 512],
  fontSizes: [12, 14, 16, 18, 20, 22, 24, 32, 40, 48, 64],
  fontWeights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  colors: {
    text: 'rgba(var(--text-color), 0.9)',
    background: 'rgb(var(--background-color))',
    backgroundLighten10: 'rgb(var(--backgroundLighten10-color))',
    backgroundLighten20: 'rgb(var(--backgroundLighten20-color))',
    primaryDarken: 'rgb(var(--primaryDarken-color))',
    primary: 'rgb(var(--primary-color))',
    primaryLighten10: 'rgb(var(--primaryLighten10-color))',
    primaryLighten50: 'rgb(var(--primaryLighten50-color)',
    primaryLighten70: 'var(--primaryLightsen70-color))',
    secondary: 'rgb(var(--secondary-color))',
  },
  radii: [5, '50%'],
  fontWeights: {
    body: 400,
    heading: 900,
  },
  lineHeights: {
    body: 1.675,
    heading: 1.125,
  },
  letterSpacings: {
    heading: '1.5',
  },
  fonts: fonts,
  nav: {
    logo: {
      flexDirection: 'column',
      justifyContent: 'center',
      a: { textDecoration: 'none' },
      container: {
        p: 3,
        display: ['flex', 'none'],
        visibility: ['visible', 'hidden'],
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
    },
  },
  header: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: config.headerImageHeight,
    color: 'text',
    fontFamily: 'heading',
    'h1, h5': { m: 0 },
    h1: { fontSize: [6, 8], mt: [2, 0] },
    h5: { mt: 1, fontSize: 1, opacity: 0.2 },
    '.header_content': {
      width: '100%',
      height: '100%',
      position: 'absolute',
      // pb: [5, 8],
      px: [5, 8],
      zIndex: 1,
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      button: {
        width: '100%',
        maxWidth: 7,
        height: 7,
        background: 'transparent',
        color: 'text',
        fontSize: '1em',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        border: 'none',
        mr: 3,
        mt: 2,
        svg: {
          mt: '1px',
          ml: '2px',
        },
      },
    },
  },
  styles: {
    color: 'primary',
    root: {
      '.episodes_list': {
        backgroundColor: 'background',
        position: ['absolute', 'static'],
        zIndex: 2,
        width: '100%',
        maxWidth: [375, 300],
        px: 5,
        pt: 40,
        a: {
          textDecoration: 'none',
          color: 'text',
          fontSize: 3,
          fontWeight: 'heading',
        },
        li: {
          py: 0,
          display: 'flex',
          justifyContent: 'flex-start',
          alignItems: 'center',
          '.summary': {
            fontSize: 2,
            lineHeight: 1.4,
            fontWeight: 300,
            opacity: 0.7,
            mt: 3,
          },
          '.active': {
            borderLeft: '3px solid',
            borderColor: 'primary',
            backgroundColor: 'backgroundLighten10',
          },
          a: {
            px: 2,
            py: 4,
            borderLeft: '3px solid',
            borderColor: 'background',
            fontSize: 4,
            width: '100%',
          },
          ':hover': {
            a: { borderColor: 'backgroundLighten10' },
            '.active': {
              borderColor: 'primary',
            },
          },
          h4: {
            mb: 0,
          },
          button: {
            position: 'relative',
            opacity: 1,
            ml: 2,
            mr: 5,
            color: 'primary',
            display: 'flex',
            width: '100%',
            maxWidth: 5,
            height: 5,
            flexGrow: '1',
            border: '0px',
            borderRadius: '50%',
            borderColor: 'background',
            alignItems: 'center',
            justifyContent: 'center',
            svg: { mt: '0px', ml: '1px' },
            cursor: 'pointer',
          },
        },
      },
      '[data-reach-skip-link]': {
        border: '0',
        clip: 'rect(0 0 0 0)',
        height: '1px',
        width: '1px',
        margin: '-1px',
        padding: '0',
        overflow: 'hidden',
        position: 'absolute',
        zIndex: '999',
      },
      '[data-reach-skip-link]:focus': {
        padding: '1rem',
        position: 'fixed',
        top: '10px',
        left: '10px',
        backgroundColor: 'background',
        width: 'auto',
        height: 'auto',
        clip: 'auto',
      },
      backgroundColor: 'background',
      lineHeight: 'body',
      fontFamily: 'body',
      fontSize: [2, 3],
      color: 'text',
      bg: 'background',
      a: {
        color: 'primary',
      },
      'a:hover': {
        color: 'primaryLighten70',
      },
      'a.btn': {
        color: 'background',
      },
      article: {
        p: [5, 8],
        pb: [2, 14],
        borderLeft: '2px solid',
        borderRight: '2px solid',
        borderBottom: '2px solid',
        borderColor: 'backgroundLighten10',
      },
      '.sidebar': {
        display: 'flex',
        flexDirection: 'column',
        p: [5, 8],
        pb: [13, 8],
        width: '100%',
        maxWidth: ['100%', 300],
        fontSize: '15px',
        h5: { my: 4, fontSize: 3 },
        'h5:not(:first-of-type)': { mb: 10, mt: 0 },
        '.guest': {
          fontSize: 1,
          textTransform: 'uppercase',
          opacity: 0.8,
          fontWeight: 'body',
        },

        li: {
          mb: 2,
          display: 'flex',
          a: { color: 'text' },
          svg: {
            mt: 1,
            mr: 1,
            width: '100%',
            maxWidth: 3,
            color: 'text',
            opacity: 0.5,
          },
        },
      },
      hr: {
        backgroundColor: 'backgroundLighten10',
        height: '2px',
      },
    },
    a: {
      color: 'primary',
      textDecoration: 'none',
      ':hover': {
        color: 'secondary',
        textDecoration: 'underline',
      },
    },
  },
};
